-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN (SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_CAR 
            WHERE CAR_TYPE = '세단') T ON T.CAR_ID = H.CAR_ID
WHERE TO_CHAR(START_DATE, 'mm') = '10'
ORDER BY H.CAR_ID DESC;