-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT O.ANIMAL_ID, O.NAME, (O.DATETIME-I.DATETIME) AS DATETIME
      FROM ANIMAL_INS I
      INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
      ORDER BY DATETIME DESC)
WHERE ROWNUM <= 2