-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME -- 5 : 필드 출력
FROM ANIMAL_INS INS -- 1 : 들어온 동물 정보
LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID -- 2 : ID기준 LEFT 조인
WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%' -- 3 : 들어올 때 중성화X AND
AND (OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%' OR OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%') -- 4 : 나갈 때 중성화O