SELECT UGU.USER_ID, UGU.NICKNAME, UGB.PRICE AS TOTAL_SALES 
FROM USED_GOODS_USER UGU, (SELECT WRITER_ID, SUM(PRICE) AS PRICE
                           FROM USED_GOODS_BOARD UGB
                           GROUP BY WRITER_ID, STATUS
                           HAVING STATUS = 'DONE'
                           AND SUM(PRICE) >= 700000) UGB
WHERE UGU.USER_ID = UGB.WRITER_ID
ORDER BY TOTAL_SALES