SELECT TO_CHAR(AA.SALES_DATE, 'YYYY-MM-DD'), AA.PRODUCT_ID, AA.USER_ID, AA.SALES_AMOUNT
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYYMM') LIKE '202203'

    UNION ALL

    SELECT SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'YYYYMM') LIKE '202203') AA
ORDER BY AA.SALES_DATE, AA.PRODUCT_ID, AA.USER_ID
