SELECT FLAVOR
FROM (SELECT FH.FLAVOR, (FH.TOTAL_ORDER  + J.TOTAL_ORDER) AS TOTAL_ORDER
    FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) J
    INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
                FROM FIRST_HALF
                GROUP BY FLAVOR) FH ON J.FLAVOR = FH.FLAVOR
    ORDER BY TOTAL_ORDER DESC)
WHERE ROWNUM <=3