SELECT DISTINCT(CC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH ON CC.CAR_ID = CH.CAR_ID
WHERE TO_CHAR(CH.START_DATE, 'MM') = 10 AND CC.CAR_TYPE LIKE '세단'
ORDER BY CAR_ID DESC