# Generated by Django 4.1.7 on 2023-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default=1, max_length=20, verbose_name='비밀번호'),
            preserve_default=False,
        ),
    ]
