# Generated by Django 4.1.7 on 2023-04-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
