-- 코드를 입력하세요
SELECT MP.MEMBER_NAME,
        RR.REVIEW_TEXT, 
    TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD')
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                        FROM REST_REVIEW
                        GROUP BY MEMBER_ID)
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;