SELECT A.HOUR AS HOUR  , COUNT(B.ANIMAL_TYPE) AS COUNT FROM 
(SELECT LEVEL -1 AS HOUR FROM DUAL 
CONNECT BY LEVEL <=24 ) A
LEFT JOIN ANIMAL_OUTS B ON 
TO_CHAR(DATETIME , 'HH24') = A.HOUR 
 GROUP BY HOUR
 ORDER BY A.HOUR
