-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
           FROM FOOD_ORDER 
           WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') = '202205'
           GROUP BY PRODUCT_ID) FO 
           ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID