SELECT GB.TITLE, GR.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY GR
INNER JOIN USED_GOODS_BOARD GB ON GR.BOARD_ID = GB.BOARD_ID
WHERE DATE_FORMAT(GB.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE, GB.TITLE